logging:
  level:
    root: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 80

spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
#h2 -console
  h2:
    console:
      enabled: true

#dev-tools
  devtools:
    livereload:
      enabled: true
#datasource
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      jdbc-url: jdbc:h2:tcp://localhost:1521/data


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
